name: Sync to Gitee

on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Gitee
        uses: wearerequired/git-mirror-action@master
        with:
          destination_repo: "git@gitee.com:zane-cao/zane-sr.git"
          ssh_private_key: ${{ secrets.GITEE_SSH_PRIVATE_KEY }}
          source_branch: "master"
